### ISSUE TITLE
Cannot "npm install": Cannot find module 'david-www/node_modules/level-session/node_modules/generic-session/node_modules/keygrip/install.js'

### ISSUE THREAD

**Issue by marcellodesales** [alanshaw/david-www#183]
Hi there,

I'm trying to build david and I cannot :(

```
$ npm instal
 
> keygrip@0.2.4 install /app_local/installs/david-www/node_modules/level-session/node_modules/generic-session/node_modules/keygrip
> [ -x /usr/bin/nodejs ] && /usr/bin/nodejs ./install.js || node ./install.js

-
module.js:340
    throw err;
          ^
Error: Cannot find module '/app_local/installs/david-www/node_modules/level-session/node_modules/generic-session/node_modules/keygrip/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm WARN optional dep failed, continuing keygrip@0.2.4
npm WARN optional dep failed, continuing fsevents@0.3.5
-
```

The install keeps going and fails with the node-gyp error... But it exists..

```
> leveldown@0.10.4 install /app_local/installs/david-www/node_modules/level/node_modules/leveldown
> node-gyp rebuild

sh: node-gyp: command not found
npm ERR! Linux 2.6.32-431.1.2.el6.x86_64
npm ERR! argv "node" "/usr/bin/npm" "instal"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! leveldown@0.10.4 install: `node-gyp rebuild`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the leveldown@0.10.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app_local/installs/david-www/npm-debug.log
```

I have all the needed dependencies:

```
$ node-gyp --version
v1.0.3
```

What else could that be? I'm on RHEL 6.5...

thanks!
Marcello

**Comment by elimcjah** [comment]
Noice.
