### ISSUE TITLE
[Error] Unhandled "type" parameter errors 

### ISSUE THREAD

**Issue by OmarTrigui** [alanshaw/david-www#363]
The input needs to be sanitized !
```
$ curl http://localhost:1337/alanshaw/grunt-jsio?type=()
SyntaxError: Unexpected token < in JSON at position 0
   at JSON.parse (<anonymous>)
   at [My PATH]/david-www/node_modules/node-fetch/lib/body.js:48:15
   at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by alanshaw** [comment]
Thanks @OmarTrigui, will you send a pull request?

**Comment by OmarTrigui** [comment]
Yes, done.

**Comment by OmarTrigui** [comment]
Yes, done.

**Comment by rosid86** [comment]
$ curl http://localhost:1337/alanshaw/grunt-jsio?type=()
SyntaxError: Unexpected token < in JSON at position 0
   at JSON.parse (<anonymous>)
   at [My PATH]/david-www/node_modules/node-fetch/lib/body.js:48:15
   at process._tickCallback (internal/process/next_tick.js:103:7)
