### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:3001

### ISSUE THREAD

**Issue by mrseanryan** [alanshaw/david-www#443]
Hopefully this is a config issue - but am raising it, as am stuck.

I followed the README and created a github PAT and added it to a new .davidrc file.

`npm start` does start up the website - and it is able to retrieve latest updates from npm

BUT if I try to use a URL to view a particular package, there is an error reaching local port 3001

```
curl http://localhost:1337/alanshaw/grunt-jsio

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>FetchError: request to http://localhost:3001/gh/alanshaw/grunt-jsio failed, reason: connect ECONNREFUSED 127.0.0.1:3001<br> &nbsp; &nbsp;at ClientRequest.&lt;anonymous&gt; (/Users/Sean.Ryan/src/github/mrseanryan/david-www/node_modules/node-fetch/index.js:133:11)<br> &nbsp; &nbsp;at ClientRequest.emit (events.js:314:20)<br> &nbsp; &nbsp;at Socket.socketErrorListener (_http_client.js:428:9)<br> &nbsp; &nbsp;at Socket.emit (events.js:314:20)<br> &nbsp; &nbsp;at emitErrorNT (internal/streams/destroy.js:92:8)<br> &nbsp; &nbsp;at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:84:21)</pre>
</body>
</html>
```

1. Is there some config step I need to add?

2. which PAT elements need to be enabled?  (github has a long list of permissions that can be enabled)

Thank you!

**Comment by mrseanryan** [comment]
`projectApiUrl` is pointing to 'http://localhost:3001'

but there is no service running ...
